### PR TITLE
docs: add architecture diagram

### PR DESCRIPTION
**Pull request by allforabit**
Add an architecture diagram to show the flow setting up 2FA and setting up tokens. The Google Slides doc is here https://docs.google.com/presentation/d/16038cTBefSKQezJk0IZKNXnSqaG2PnU07Sb2_qIkNe8/edit?usp=sharing and is linked in the readme.

architecture
.

### CODE REVIEW

**Review by simoneb — APPROVED** [review]
Overall the diagram looks good except that this is not really an architecture diagram, this is a sequence diagram. Let's reflect this and we're good.

**Comment by simoneb** [comment]
Also, not sure if it's a GH glitch but when I preview your change I don't see the image

image

**Comment by simoneb** [comment]
@kevindevine as always, please link the issue

**Comment by allforabit** [comment]
Yes sorry done now I think you've pinged the wrong Kevin there :-)

**Comment by simoneb** [comment]
> Yes sorry done now I think you've pinged the wrong Kevin there :-)

Yeah typical

**Pull request merged**
