### PR TITLE
feat: track pending notifications

### LINKED ISSUE #420: Show OTP requests on application open
Using the android app, if I miss the notification because I wipe out unfortunately or for whatever reason, I can not see the pending OTP requests by opening the application.

Is it possible to track all the OTP requests received and the status (waiting, approved, rejected, timeout)?

### PR DESCRIPTION
**Pull request by castarco**
## Changes
- Adds a new "notifications" section, where all pending notifications are listed to be handled (rejected, accepted, or dismissed in case they already expired).
- The pending notifications are persisted.
- The push notifications are automatically dismissed if the OTP requests are handled directly via the notifications section instead of doing that through the notifications provided by the smartphone's interface.

## About the scope
- For now, we don't keep track of all previous accepted & rejected OTP requests (once we handle them, we discard this information). I believe this should be discussed with more people, as it's a more advanced feature resembling a sort of audit log, and we might want to have support from the API side.

## Shortcomings
- Right now, the "notifications bell" does not have a nice numerical counter, it just turns to red instead when we have pending notifications. Before the reviews finish, I'll try to discover how to do that with our components. If don't arrive in time, we could defer it to another smaller PR.

Fixes #420 .

### CODE REVIEW

**Review by rp4rk — APPROVED** [review]
LGTM 👍

**Comment by simoneb** [comment]
@rp4rk once the preview is deployed can you test it out perhaps?

**Review by simoneb — APPROVED** [review]
Overall LGTM. For the badge containing the number of notifications, did you look into this approach? https://github.com/callstack/react-native-paper/issues/1466

**Comment by castarco** [comment]
@simoneb I discovered it late, thank you for the reference, I already prepared a different branch for it.

**Pull request merged**
