### PR TITLE
docs: document release certificate generation process

### PR DESCRIPTION
**Pull request by williamlines**
Documenting the process for creating new certificates for releases to the iOS App Store.

closes: https://github.com/nearform/optic-expo/issues/1278

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
All good for me, just making sure we're not disclosing sensitive information in the screenshots especially, right? This repo is public.

**Review by simoneb — COMMENTED** [review]
Also one Q: why would the certificate expire in the first place? Is there a way to prevent that from happening?

**Comment by williamlines** [comment]
@simoneb The max duration you can specify for a certificate is one year, unfortunately. So this will need to be an ongoing consideration

**Comment by williamlines** [comment]
> All good for me, just making sure we're not disclosing sensitive information in the screenshots especially, right? This repo is public.

I think this is safe but I will double check with Manos

**Comment by williamlines** [comment]
The screenshot is safe to share

**Review by simoneb — APPROVED** [review]
LGTM, thanks @williamlines and @manosim for looking into it

**Pull request merged**
