### PR TITLE
fix: 869: fix expo doctor package version issues

### PR DESCRIPTION
**Pull request by lasmil**
- closes https://github.com/nearform/optic-expo/issues/869
- to be able to run the ci build, we need to able to run the  'yarn doctor' command
- this PR updates the problematic packages
- this should also fix the dependabot created PR build issues

### CODE REVIEW

**Comment by simoneb** [comment]
@lasmil thanks for this. as part of this work I would like us to understand why this happens, as I've seen this happen in the past but I don't understand why.

- we run doctor in CI, meaning that no incompatible dependencies should be merged
- yet it looks like that for some reason incompatible dependencies still make their way into the master branch

Can we figure out why?

**Comment by lasmil** [comment]
> @lasmil thanks for this. as part of this work I would like us to understand why this happens, as I've seen this happen in the past but I don't understand why.
> 
> * we run doctor in CI, meaning that no incompatible dependencies should be merged
> * yet it looks like that for some reason incompatible dependencies still make their way into the master branch
> 
> Can we figure out why?

I looked into what are the possible explanations for this. Other than manually adding specific versions into package.json, I can't seem to find out why this could have happened.
The last successful PR was the dependabot triggered [expo version update](https://github.com/nearform/optic-expo/pull/862). I checked out these changes and yarn doctor fails for me as well.

Maybe @SociableSteve can give an opinion (or suggest somebody who can help) on how can yarn doctor miss these dependency related problems.

Other than this, I would try to see if these changes (in this PR) can actually fix the other open PRs build problems and then keep an eye open to certain package.json changes (dependabot and not dependabot triggered). Maybe even manually running a yarn doctor command on these to try to catch the issue.

**Comment by simoneb** [comment]
dependabot should be the only way that changes to package.json make their way to the main branch, so I guess we still don't know why this is happening.

**Review by simoneb — APPROVED** [review]

**Comment by lasmil** [comment]
> dependabot should be the only way that changes to package.json make their way to the main branch, so I guess we still don't know why this is happening.

I will keep an eye open to see if I can spot this happening in future PRs. Maybe we can find something.

**Pull request merged**
