### PR TITLE
upgrade expo to 45, remove deprecated expo-app-loading

### LINKED ISSUE #521: Upgrade to expo 45
See https://github.com/nearform/optic-expo/pull/520 (or newer dependabot PR) and look at the migration docs

### PR DESCRIPTION
**Pull request by aledgjones**
Closes #521

expo-app-loading is deprecated and as suggested in the deprecation notice this PR includes a migration to use expo-splash-screen directly

### CODE REVIEW

**Comment by simoneb** [comment]
what's the status of this PR?

**Comment by aledgjones** [comment]
I am still seeing linting errors in the react-native-reanimated package which I have been unable to resolve. These errors are to do with the global definitions. I have tried to create a minimal, reproducible example but I'm unable to replicate the issue so this needs further investigation.

**Comment by simoneb** [comment]
It's ok, we can put this on hold if we can't find a solution. Can you rebase on master just to make sure we're aligned with whatever changes were merged there?

**Comment by simoneb** [comment]
Closing in favor of #627

**Pull request closed without merging**
